#!/bin/bash
#
# Hello World test c++ code

clear

#compile with:
rm spawn 2>/dev/null

g++ -std=c++0x -pthread main.cpp -o spawn -lrt; ./spawn

exit
# the -pthread  option is needed on older versions of gcc
# the -lrt option is used for time.h to get elapsed nanoseconds
#   since std::chrono only provided microseconds


# PROCESSOR STATUS INFO
/*    proc/stat contents
from: http://www.linuxhowtos.org/System/procstat.htm


The very first "cpu" line aggregates the numbers in all of the other "cpuN" lines.

These numbers identify the amount of time the CPU has spent performing different kinds of work. Time units are in USER_HZ or Jiffies (typically hundredths of a second).

The meanings of the columns are as follows, from left to right:

user: normal processes executing in user mode
nice: niced processes executing in user mode
system: processes executing in kernel mode
idle: twiddling thumbs
iowait: waiting for I/O to complete
irq: servicing interrupts
softirq: servicing softirqs
The "intr" line gives counts of interrupts serviced since boot time, for each
of the possible system interrupts. The first column is the total of all interrupts serviced; each subsequent column is the total for that particular interrupt.



The "ctxt" line gives the total number of context switches across all CPUs.



The "btime" line gives the time at which the system booted, in seconds since
the Unix epoch.



The "processes" line gives the number of processes and threads created, which includes (but is not limited to) those created by calls to the fork() and clone() system calls.



The "procs_running" line gives the number of processes currently running on CPUs.



The "procs_blocked" line gives the number of processes currently blocked, waiting for I/O to complete.

copied from the kernel documentation of the /proc filesystem

Note: On my 2.6.18 kernel, cpu lines have 8 numeric fields, not 7. 
Wonder what that one means...

Note:
The 8th column is called steal_time. It counts the ticks spent
executing other virtual hosts (in virtualised environments like Xen)

Note2:
With Linux 2.6.24 there is 9th column for (virtual) guest systems. See man 5 proc.
*/


